apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - api/deploy.yaml
  - api/service.yaml
  - api/ingress.yaml
configMapGenerator:
  - files:
      - configs/config.yaml
    name: app-config